# System-wide .bashrc file for interactive bash(1) shells.
if [ -z "$PS1" ]; then
   return
fi

PS1='\h:\W \u\$ '
# Make bash check its window size after a process completes
shopt -s checkwinsize

[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"

export BASH_SILENCE_DEPRECATION_WARNING=1

#enable vi-mode
set -o vi
#added aliases
alias ls='ls -lah'
alias date='date | lolcat && cal'

alias pRun='processing-java --sketch=$PWD --run'
