#!/bin/bash

canvasGen () {

	colors=("snow" "snow1" "snow2" "RosyBrown1" "RosyBrown2" 
		"snow3" "LightCoral" "IndianRed1" "RosyBrown3" "IndianRed2" "RosyBrown" 
		"brown1""firebrick1" "brown2" "IndianRed" "IndianRed3" "firebrick2" "snow4" 
		"brown3" "red" "red1" "RosyBrown4" "firebrick3" "red2" "firebrick" "brown"
		"IndianRed4" "brown4" "firebrick4" "DarkRed" "red4" "maroon" "LightPink1" 
		"LightPink2" "LightPink3" "LightPink4" "LightPink" "pink" "crimson" "pink1" 
		"pink2"	"pink3" "pink4" "PaleVioletRed4" "PaleVioletRed" "PaleVioletRed2" 
		"PaleVioletRed1" "PaleVioletRed3" "LavenderBlush" "LavenderBlush1" 
		"LavenderBlush3" "LavenderBlush2" "LavenderBlush4" "HotPink3" "VioletRed3"
		"VioletRed1" "VioletRed2" "VioletRed4" "HotPink2" "HotPink1" "HotPink4" 
		"HotPink" "DeepPink" "DeepPink1" "DeepPink2" "DeepPink3" "DeepPink4"
	 	"maroon1" "maroon2" "maroon3" "maroon4" "MediumVioletRed" "VioletRed" 
		"orchid2" "orchid" "orchid1" "orchid3" "orchid4" "thistle1" "thistle2"  
		"plum1" "plum2" "thistle" "thistle3" "plum" "violet" "plum3" "thistle4" 
		"fuchsia" "magenta" "plum4" "magenta2" "magenta3" "DarkMagenta" "magenta4"
		"purple" "MediumOrchid" "MediumOrchid1" "MediumOrchid2" "MediumOrchid3" 
		"MediumOrchid4" "DarkViolet" "DarkOrchid" "DarkOrchid1" "DarkOrchid3" 
		"DarkOrchid2" "DarkOrchid4" "indigo" "BlueViolet" "purple2" "purple3" 
		"purple4" "purple1" "MediumPurple" "MediumPurple1" "MediumPurple2" 
		"MediumPurple3" "MediumPurple4" "DarkSlateBlue" "LightSlateBlue"
		"MediumSlateBlue" "SlateBlue" "SlateBlue1" "SlateBlue2" "SlateBlue3" 
		"SlateBlue4" "GhostWhite" "lavender" "blue" "blue1" "blue2" "blue3" 
		"MediumBlue" "blue4" "DarkBlue" "MidnightBlue" "nacy" "NavyBlue"
		"RoyalBlue" "RoyalBlue1" "RoyalBlue2" "RoyalBlue3" "RoyalBlue4"
		"CornFlowerBlue" "LightSteelBlue" "LightSteelBlue1" "LightSteelBlue2" 
		"LightSteelBlue3" "LightSteelBlue4" "SlateGray4" "SlateGray1" "SlateGray2" 
		"SlateGray3" "LightSlateGrey" "SlateGrey" "DodgerBlue" "DodgerBlue1" 
		"DodgerBlue2" "DodgerBlue4" "DodgerBlue3" "AliceBlue" "SteelBlue4"
		"SteelBlue" "SteelBlue1" "SteelBlue2" "SteelBlue3" "SteelBlue4" "SkyBlue1" 
		"SkyBlue2" "SkyBlue3" "LightSkyBlue" "LightSkyBlue4" "LightSkyBlue1" 
		"LightSkyBlue2" "LightSkyBlue3" "SkyBlue" "LightBlue3" "DeepSkyBlue" 
		"DeepSkyBlue1" "DeepSkyBlue2" "DeepSkyBlue4" "DeepSkyBlue3" "LightBlue1"
		"LightBlue2" "LightBlue" "LightBlue4" "PowderBlue" "CadetBlue1" 
		"CadetBlue2" "CadetBlue3" "CadetBlue4" "turquoise1" "turquoise2" 
		"turquoise3" "turquoise4" "cadet blue" "CadetBlue" "DarkTurquoise" "azure" 
		"azure1" "LightCyan" "LightCyan1" "azure2" "LightCyan2" "PaleTurquoise1" 
		"PaleTurquoise" "PaleTurquoise2" "DarkSlateGray1" "azure3" "LightCyan3" 
		"DarkSlateGrey2" "PaleTurquoise3" "azure4" "LightCyan4" 
		"aqua" "cyan" "cyan1" "PaleTurquoise4" "cyan2" "DarkSlateGrey4" "cyan3" 
		"cyan4" "DarkCyan" "teal" "DarkSlateGrey" "MediumTurquoise" "LightSeaGreen" 
		"turquoise" "aquamarine4" "aquamarine" "aquamarine1" "aquamarine2" 	
		"aquamarine3" "MediumAquamarine" "MediumSpringGreen" "MintCream"
		"SpringGreen" "SpringGreen1" "SpringGreen2" "SpringGreen3" "SpringGreen4" 
		"MediumSeaGreen" "SeaGreen" "SeaGreen3" "SeaGreen1" "SeaGreen4" "SeaGreen2" 
		"MediumForestGreen" "honeydew" "honeydew1" "honeydew2" "honeydew3"
		"honeydew4" "DarkSeaGreen1" "DarkSeaGreen2" "DarkSeaGreen3" "DarkSeaGreen4" 
		"PaleGreen1" "PaleGreen" "LgihtGreen" "PaleGreen2" "DarkSeaGreen"
		"PaleGreen3" "honeydew4" "green1" "lime" "LimeGreen" "green2" "PaleGreen4" 
		"green3" "ForestGreen" "green4" "green" "DarkGreen" "LawnGreen" 
		"chartreuse" "chartreuse1" "chartreuse2" "chartreuse3" "chartreuse4" 
		"GreenYellow" "DarkOliveGreen" "DarkOliveGreen1" "DarkOliveGreen2" 
		"DarkOliveGreen3" "DarkOliveGreen4" "YellowGreen" "OliveDrab" "OliveDrab1"
	 	"OliveDrab2" "OliveDrab3" "OliveDrab4" "ivory1" "ivory2" "ivory3" "ivory4" 
		"ivory" "LightYellow1" "LightYellow2" "LightYellow3" "LightYellow4" 
		"LightYellow" "beige" "LightGoldenrodYellow" "yellow1" "yellow2" "yellow3" 
		"yellow4" "yellow" "olive" "DarkKhaki" "khaki1" "khaki2" "khaki3" "khaki4" 
		"khaki" "LemmonChiffon" "LemmonChiffon1" "LemmonChiffon2" "LemmonChiffon3" 
		"LemmonChiffon4" "PaleGoldenrod" "MediumGoldenRod" "cornsilk" "cornsilk1" 
		"cornsilk2" "cornsilk3" "cornsilk4" "gold" "gold1" "gold2" "gold3" "gold4" 
		"LightGoldenrod" "LightGoldenrod1" "LightGoldenrod2" "LightGoldenrod3"
		"LightGoldenrod4" "goldenrod" "goldenrod1" "goldenrod2" "goldenrod3"
		"goldenrod4" "DarkGoldenrod" "DarkGoldenrod1" "DarkGoldenrod2"
		"DarkGoldenrod3" "DarkGoldenrod4" "FloralWhite" "wheat" "wheat1" "wheat2"
		"wheat3" "wheat4" "OldLace" "orange" "orange1" "orange2" "orange3" 
		"orange4" "moccasin" "PapayaWhip" "NavajoWhite" "NavajoWhite1"
		"NavajoWhite2" "NavajoWhite3" "NavajoWhite4" "BlanchedAlmond" 
		"AntiqueWhite" "AntiqueWhite1" "AntiqueWhite2" "AntiqueWhite3" 
		"AntiqueWhite4" "tan" "tan1" "tan2" "tan3" "tan4" "bisque" "bisque1"
		"bisque2" "bisque3" "bisque4" "burlywood" "burlywood1" "burlywood2"
		"burlywood3" "burlywood4" "DarkOrange" "DarkOrange1" "DarkOrange2"
		"DarkOrange3" "DarkOrange4" "linen" "peru" "PeachPuff" "PeachPuff1"
		"PeachPuff2" "PeachPuff3" "PeachPuff4" "SandyBrown" "seashell" "seashell1"
		"seashell2" "seashell3" "seashell4" "chocolate" "chocolate1" "chocolate2"
		"chocolate3" "chocolate4" "SaddleBrown" "sienna" "sienna1" "sienna2"
		"sienna3" "sienna4" "LightSalmon" "LightSalmon1" "LightSalmon2"
		"LightSalmon3" "LightSalmon4" "coral" "coral1" "coral2" "coral3" "coral4" 
		"OrangeRed" "OrangeRed1" "OrangeRed2" "OrangeRed3" "OrangeRed4" "salmon"
		"salmon1" "salmon2" "salmon3" "salmon4" "tomato" "tomato1" "tomato2"
		"tomato3" "tomato4" "MistyRose" "MistyRose1" "MistyRose2" "MistyRose3"
		"MistyRose4" "WhiteSmoke" "fractal" "black")

	RANDOM=$$$(date +%s)

	color1=${colors[$RANDOM % ${#colors[@]}]}	
	color2=${colors[$RANDOM % ${#colors[@]}]}	

	mkdir canvas/ && cd canvas/
  
  convert -size 4131x3066  plasma:$color1-$color2 canvasBg.png;

	magick canvasBg.png -spread 50 +gamma 8 canvasProcessed.png 	

	mv canvasProcessed.png canvasFinal_${color1}_${color2}.png

	cd ..

	exit

}

canvasGen 
