#!/bin/bash

lolRandom () {
	
	randGen | lolcat

}

randGen () {

	lengthOfLine=22

  for i in {1..500}
  do
  	
  	declare -a randomNum
  
  	for j in $( seq 0 $lengthOfLine)
  	do
  		randomNum[j]=$(( $RANDOM % 1000))
  	done 
  
  	for k in $( seq 0 $lengthOfLine)	
  	do	
  		echo -n ${randomNum[k]} "" | awk '{printf "%03d ", $0;}'  
  	 	sleep 0.05	
  	done
  
  	echo 
  	#sleep 0.1
  
  done	

}

lolRandom 

exit
