#!/bin/bash

mkGif () {
	
	for t in "$@";
	do 
		gifProcess $t;
	done

	echo $'\nprocess complete\n\n'

	exit

}

gifProcess () {

	cd media

# create fileName var and use awk to create nExFileName var (no extention)

	echo "`ls`" > titleOfContent.txt
	ToC=$(cat titleOfContent.txt)  
	ToC_nEx=$(echo $ToC | awk -F\. '{print $1}')

	mkdir -p frames/lFrames

	for i in $ToC; 
	do 
		ffmpeg -i $ToC -ss $t -t 00:03 clip.mov; 
	done

	ffmpeg -i clip.mov -r 10 frames%2d.jpg && mv *.jpg frames

	cd frames

	cp *.jpg lFrames

	cd lFrames

	mogrify *.jpg +dither -colors 16 -resize 30% *.jpg 

	convert *.jpg -delay 40 ${t}_$ToC_nEx.gif

	rm -r -f ~/Home/prog/bashScript/mkGif/media/titleOfContent.txt

	mv *.gif ~/Home/prog/bashScript/mkGif/output

	cd ~/Home/prog/bashScript/mkGif 

	rm -r -f ~/Home/prog/bashScript/mkGif/media/clip.mov ~/Home/prog/bashScript/mkGif/media/frames

	echo $'\ngif complete\n'

}

mkGif $@
