#!/bin/bash

mkGif () {
	
	for t in "$@";
	do 
		gifProcess $t;
	done

	echo $'\nprocess complete\n\n'

	exit

}

gifProcess () {

	cd media

	mkdir -p frames/lFrames

	for i in *.mov; 
	do 
		ffmpeg -i *.mov -ss $t -t 00:03 clip.mov; 
	done

	ffmpeg -i clip.mov -r 10 frames%2d.jpg && mv *.jpg frames

	cd frames

	cp *.jpg lFrames

	cd lFrames

	mogrify *.jpg +dither -colors 16 -resize 30% *.jpg 

	convert *.jpg -delay 40 media-${t}.gif

	mv *.gif ~/myWindow/mkGif/output

	cd ~/myWindow/mkGif 

	rm -r -f ~/Home/mkGif/media/clip.mov ~/Home/mkGif/media/frames/

	echo $'\ngif complete\n'

}

mkGif $@
