#!/bin/bash

yts(){

	cd /Users/VII/Home/prog/bashScript/yts;

	for w in "$@";
	do
		echo -n "$w " >> query.txt;
	done;

	sed 's/ /+/g' query.txt > formattedQuery.txt && mv formattedQuery.txt query.txt

	/Applications/Firefox.app/Contents/MacOS/firefox https://www.youtube.com/results?search_query="`cat query.txt`";

	rm query.txt

	exit;

}

yts $@
