#!/bin/bash

FPATH='/Applications/Firefox.app/Contents/MacOS/firefox'
YTURL='https://www.youtube.com/results?search_query='

yts(){

	cd /Users/VII/Home/prog/bashScript/yts;

	for w in "$@";
	do
		echo -n "$w " >> query.txt;
	done;

	sed 's/ /+/g' query.txt > formattedQuery.txt 
	
	mv formattedQuery.txt query.txt;

	$FPATH $YTURL"`cat query.txt`";

	rm query.txt;

	exit;

}

yts $@
